# Generated by Django 3.2.15 on 2022-08-31 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0002_auto_20220830_1615'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='number_of_answers',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='number_of_questions',
            field=models.IntegerField(default=0),
        ),
    ]
