# Generated by Django 3.2.15 on 2022-09-05 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0007_user_short_about_me'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='description',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
